### ISSUE TITLE
Artifacts are not accessible on MoveApps

### ISSUE THREAD

**Issue by cleemansen** [Bo-Brown-Dev/Road-Crossings#2]
Hello,

this is a follow up of https://github.com/movestore/python-sdk/issues/6.

I've noticed the following issue about the artifacts handling:

1. `appspec.json`: the content of this file is case-sensitive. Please change from `"CreatesArtifacts": true` to `"createsArtifacts": true`

Best,
Clemens

---

And as a side note: I've noticed that your app has a remarkable memory footprint (RAM). A small input (1 animal, ~ `300kb` pickle file-size) results in a memory consumption of nearly `3GB`. 
This is off course off-topic - but be aware that each app on MoveApps currently gets a maximum of `3GB` memory. And unfortunately raising this limit results in a hard app crash (OOM exception). In many cases this exception does not result in a understandable error message for the user on MoveApps. Just in case you notice app errors on MoveApps. Perhaps you can optimize your app regarding memory usage.

**Comment by Bo-Brown-Dev** [comment]
@cleemansen Whoopsies, thanks for the help! I'll be looking at optimizing memory over the next couple of days

**Comment by andreakoelzsch** [comment]
@Bo-Brown-Dev new App version is built. thanks
