### ISSUE TITLE
Document error "['event.id'] not in index"

### ISSUE THREAD

**Issue by sarahcd** [Bo-Brown-Dev/Road-Crossings#6]
This error occurs if an event-id is not in the data frame, for example if the user chooses "Argument Minimisation" = yes in the Movebank app. Unselecting this option solves the problem. Could be worth adding this to the "Null or error handling" section of the readme.

**Comment by Bo-Brown-Dev** [comment]
@sarahcd This is a bug, minimized arguments should be helpful to the app.

I pushed a fix to main this morning, will release new version to MoveApps this week

**Comment by sarahcd** [comment]
Thank you! I will try it when it's live.

**Comment by Bo-Brown-Dev** [comment]
@sarahcd 
New release went live, let me know if this fixes the workflow

**Comment by sarahcd** [comment]
Works! I get a different error now, will post a new issue.

**Comment by Bo-Brown-Dev** [comment]
commit 3ff5f6f41d6141380b7f96ba4ac482bcdc194b59 fixed issue
